name: Deploy to Vercel

on:
  push:
    branches:
      - hugo
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index (hugo obsidian)
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.96.0"
          extended: true

      - name: Build (with hugo)
        run: hugo --minify
      
      # - name: Deploy (to GitHub Pages)
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     publish_branch: master # deploying branch
      #     cname: <DOMAIN NAME HERE>

      - name: Deploy (to Vercel)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}   # [!] Required
          github-token: ${{ secrets.GITHUB_TOKEN }}   # Optional 
          vercel-args: '--prod'                       # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}         # [!] Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # [!] Required 
          working-directory: ./public                 # 👈 build result directory - `hugo --minify`